function display(a)
% Display a DataCommon object

stg = sprintf(...
    ['DataCommon fields -- \n',...
     '  Source        (source)     : %s\n',...
     '  Title         (title)      : %s\n',...
     '  Network       (network)    : %s\n',...
     '  Station       (station)    : %s\n',...
     '  Channel       (channel)    : %s\n',...
     '  UTC Reference (UTCref)     : %s\n',...
     '  Time Offset   (timeOffset) : %13.8f sec \n',...
     '  End Time      (timeEnd)    : %13.8f sec \n',...
     '  History       (history)    : %s'],...
    a.source, a.title, a.network, a.station, a.channel, datenum2strFull(abs(a.UTCref)), a.timeOffset, a.timeEnd, a.history);
disp(stg)
