function objects = SQLGetCMNStations()

NEWLINE = char(10);

queryString = ...
['use landers;', NEWLINE, ...
 'select name, sid, DATE_FORMAT(install_date,"%Y/%m/%d %H:%i:%S") AS sDate ', NEWLINE, ...
 'from dbase_stations', NEWLINE, ...
 'WHERE sid > 599 AND sid < 999 ', NEWLINE, ...
 ' AND sid != 697', NEWLINE, ...
 ' AND sid != 698', NEWLINE, ...
 ' AND sid != 699', NEWLINE, ...
 NEWLINE ];

% display(queryString)

objects = SQLrunQuery( queryString, 'quakedata', 'matlab' );

