function objects = SQLGetBKStations()

NEWLINE = char(10);

queryString = ...
['use xweb;', NEWLINE, ...
 'select name, ', NEWLINE, ...
 '       DATE_FORMAT(install_date,"%Y/%m/%d %H:%i:%S") AS sDate, ', NEWLINE, ...
 '       DATE_FORMAT(end_date,    "%Y/%m/%d %H:%i:%S") AS eDate  ', NEWLINE, ...
 'from ground_observatories', NEWLINE, ...
 'WHERE network="BK"', NEWLINE, ...
 NEWLINE ];

% display(queryString)

objects = SQLrunQuery( queryString, 'quakedata', 'matlab' );

