function display(a)
% Display parent
display(a.DataCommon);


stg = sprintf(...
    ['FrequencyTimeData fields -- \n',...
     '  Sample Rate       (sampleRate)     : %8.8f FFTs/sec\n', ...
     '  Freq. Resolution  (freqResolution) : %8.8f Hz\n', ...
     '  Time Axis Label   (timeAxisLabel)  : %s\n',...
     '  Freq Axis Label   (freqAxisLabel)  : %s\n',...
     '  Value Type        (valueType)      : %s\n',...
     '  Value Units       (valueUnit)      : %s\n',...
     '  Color Range       (colorRange)     : %d min, %d max\n',...
     '  Sample Count      (sampleCount)    : %d\n',...
     '  Size:                              : %d freq. x %d time points'],...
    a.sampleRate, a.freqResolution, a.timeAxisLabel, a.freqAxisLabel, ...
    a.valueType, a.valueUnit, a.colorRange(1), a.colorRange(2), numel(a.samples), size(a.samples) );

disp(stg)
