function outObj = bkHiPass( inObj )
%BKHIPASS Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
%
% Generated on: 18-Feb-2009 07:09:54
%

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 40;  % Sampling Frequency

if 0
	Fstop = 0.01;            % Stopband Frequency
	Fpass = 0.02;            % Passband Frequency
	Dstop = 0.0001;          % Stopband Attenuation
	Dpass = 0.057501127785;  % Passband Ripple
	flag  = 'scale';         % Sampling Flag

	% Calculate the order from the parameters using KAISERORD.
	[N,Wn,BETA,TYPE] = kaiserord([Fstop Fpass]/(Fs/2), [0 1], [Dpass Dstop]);

	% Calculate the coefficients using the FIR1 function.
	b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
	%Hd = dfilt.dffir(b)
else
%display('Calculating filter')
	Fstop = 0.025;           % Stopband Frequency
	Fpass = 0.05;            % Passband Frequency
	Dstop = 0.0001;          % Stopband Attenuation
	Dpass = 0.057501127785;  % Passband Ripple
	flag  = 'scale';         % Sampling Flag

	% Calculate the order from the parameters using KAISERORD.
	[N,Wn,BETA,TYPE] = kaiserord([Fstop Fpass]/(Fs/2), [0 1], [Dpass Dstop]);

	% Calculate the coefficients using the FIR1 function.
	b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
end
%display('Applying filter')

outObj = applyFilter( inObj, b, ['Highpass @ ', num2str(Fpass), ' Hz'] );


% [EOF]
