function display(a)
%
% Display parent

display(a.DataCommon);

sizor = size(a.samples);
sizeStr = sprintf( 'array of %dx%d dimension', sizor(1), sizor(2) );
if( sizor(2) > 2 )
    warning( ['TimeDat objects with more than two columns are not supported!! actual: ' sprintf( '%d', sizor(2) ) ] );
end

stg = sprintf(...
    ['TimeData fields -- \n',...
     '  Sample Rate   (sampleRate) : %12.12f samp/sec\n', ...
     '  Axis Label    (axisLabel)  : %s\n',...
     '  Value Type    (valueType)  : %s\n',...
     '  Value Units   (valueUnit)  : %s\n',...
     '  Samples       (samples)    : %s\n',...
     '  Sample Count  (sampleCount): %d'],...
    a.sampleRate, a.axisLabel, a.valueType, a.valueUnit, sizeStr, length(a.samples));

disp(stg)
